import pptxgen from 'pptxgenjs';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { BellSchedule, ClassSection, TeacherRecord, SubjectRule, TimetableSlot } from '../types';

export interface PPTXExportData {
  schoolName?: string;
  grade?: string;
  subject?: string;
  teacherName?: string;
  topPerformersCount?: number;
  remedialCount?: number;
  subjectAllocations?: { subject: string; periods: number; type: string }[];
}

/**
 * 1. AI Lesson Plan & Marks Analysis PPTX Generator (10 Slides)
 * Uses pptxgenjs according to specification
 */
export const generateLessonAndMarksPPTX = (data: PPTXExportData = {}) => {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';

  const school = data.schoolName?.trim() || 'School Timetable Report';
  const grade = data.grade || 'Grade 10';

  // Slide 1: Title Slide
  const slide1 = pptx.addSlide();
  slide1.background = { color: 'F4F7FB' };
  slide1.addText('Lesson Plan & Marks Analysis Report', {
    x: 0.8,
    y: 2.2,
    fontSize: 32,
    bold: true,
    color: '003366',
  });
  slide1.addText(`School: ${school} | Grade: ${grade}`, {
    x: 0.8,
    y: 3.4,
    fontSize: 18,
    color: '555555',
  });
  slide1.addText('Generated by TMS SL · Sri Lanka Teacher Management System', {
    x: 0.8,
    y: 4.8,
    fontSize: 12,
    color: '888888',
    italic: true,
  });

  // Slide 2: Objectives
  const slide2 = pptx.addSlide();
  slide2.addText('1. Learning Objectives & Curriculum Goals', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  slide2.addText(
    [
      { text: '- Key concept mastery in Mathematics & Science according to NIE guidelines\n', options: { breakLine: true } },
      { text: '- Practical lab application through structured double periods\n', options: { breakLine: true } },
      { text: '- Systematic remedial support for students needing improvement (<40%)\n', options: { breakLine: true } },
      { text: '- Formative continuous assessments integrated into daily lessons\n', options: { breakLine: true } },
    ],
    { x: 0.8, y: 2, fontSize: 16, lineSpacing: 28 }
  );

  // Slide 3: Subject Breakdown
  const slide3 = pptx.addSlide();
  slide3.addText('2. Weekly Subject Allocation', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });

  const tableRows: any[] = [
    [
      { text: 'Subject', options: { bold: true, fill: '003366', color: 'FFFFFF' } },
      { text: 'Periods/Week', options: { bold: true, fill: '003366', color: 'FFFFFF' } },
      { text: 'Type', options: { bold: true, fill: '003366', color: 'FFFFFF' } },
    ],
    ['Science', '5', 'Single + Double Practical (Lab)'],
    ['Mathematics', '5', 'Single Periods'],
    ['English Language', '4', 'Single Periods'],
    ['History', '3', 'Single Periods'],
    ['Information & Communication Tech (ICT)', '3', 'Double Practical (Computer Lab)'],
  ];

  slide3.addTable(tableRows, { x: 0.8, y: 1.8, w: 8.5 });

  // Slide 4: Student Marks Analysis Chart
  const slide4 = pptx.addSlide();
  slide4.addText('3. Class Marks Performance Analysis', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  slide4.addChart(
    pptx.ChartType.bar,
    [
      {
        name: 'Pass Rate %',
        labels: ['A Grade', 'B Grade', 'C Grade', 'S Grade', 'F Grade'],
        values: [35, 25, 20, 15, 5],
      },
    ],
    { x: 1, y: 1.8, w: 8, h: 4.5 }
  );

  // Slide 5: High Performers & Needy List
  const slide5 = pptx.addSlide();
  slide5.addText('4. Student Performance Segmentation', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  const topCount = data.topPerformersCount || 12;
  const remCount = data.remedialCount || 4;
  slide5.addText(
    `Top Performers (>75% A-Grade): ${topCount} Students\nRemedial Action Needed (<40%): ${remCount} Students`,
    { x: 0.8, y: 2, fontSize: 18, color: '222222', lineSpacing: 32 }
  );

  // Slide 6: AI Recommended Strategies
  const slide6 = pptx.addSlide();
  slide6.addText('5. AI Teaching Strategies & Action Items', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  slide6.addText(
    [
      { text: '• Interactive problem-solving in allocated double periods\n', options: { breakLine: true } },
      { text: '• Weekly short diagnostic quizzes for lower-scoring syllabus topics\n', options: { breakLine: true } },
      { text: '• Peer-assisted learning groups during activity exploration phases\n', options: { breakLine: true } },
      { text: '• Step-by-step visual scaffolds and bilingual vocabulary sheets\n', options: { breakLine: true } },
    ],
    { x: 0.8, y: 2, fontSize: 16, lineSpacing: 28 }
  );

  // Slide 7: Lab & Practical Schedule
  const slide7 = pptx.addSlide();
  slide7.addText('6. Practical Lab & Field Work Schedule', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  slide7.addText(
    'Double Period Slots Allocated: Wednesdays P3 & P4 (Science Lab)\nICT Lab Double Slot: Fridays P5 & P6 (Computer Laboratory)',
    { x: 0.8, y: 2, fontSize: 18, lineSpacing: 30 }
  );

  // Slide 8: Assessment Plan
  const slide8 = pptx.addSlide();
  slide8.addText('7. Assessment Matrix', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  slide8.addText(
    'Formative Continuous Assessment: 30%\nMid-Term Evaluation: 30%\nEnd-of-Term Zonal / Provincial Examination: 40%',
    { x: 0.8, y: 2, fontSize: 18, lineSpacing: 30 }
  );

  // Slide 9: Homework & Resource Requirements
  const slide9 = pptx.addSlide();
  slide9.addText('8. Required Resources & Homework Plan', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  slide9.addText(
    'Textbook Chapters 4-6, Science Lab Chemical Kits, Digital Worksheets,\nPast Paper Question Bank (2020-2025), and Student Workbook Assignments.',
    { x: 0.8, y: 2, fontSize: 18, lineSpacing: 30 }
  );

  // Slide 10: Teacher Conclusion
  const slide10 = pptx.addSlide();
  slide10.addText('9. Remarks & Sign-off', {
    x: 0.5,
    y: 0.8,
    fontSize: 24,
    bold: true,
    color: '003366',
  });
  slide10.addText(
    `Prepared By: ${data.teacherName || 'Subject Teacher'}\nApproved By: Section Head / Principal\nSchool: ${school}\nDate: ${new Date().toLocaleDateString()}`,
    { x: 0.8, y: 2, fontSize: 18, lineSpacing: 32 }
  );

  // Export File
  pptx.writeFile({ fileName: `TMS_LessonPlan_Marks_${data.grade || 'Report'}.pptx` });
};

/**
 * 2. Excel Export (using xlsx)
 * Exports:
 *  - Sheet 1: Master Timetable
 *  - Sheet 2: Class-Wise Timetables
 *  - Sheet 3: Teacher Workload Summary
 */
export const exportTimetableToExcel = (params: {
  schoolName: string;
  bellSchedule: BellSchedule;
  classes: ClassSection[];
  teachers: TeacherRecord[];
  subjectRules: SubjectRule[];
  slots: TimetableSlot[];
}) => {
  const { schoolName, bellSchedule, classes, teachers, slots } = params;
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
  const workbook = XLSX.utils.book_new();

  // --- SHEET 1: Master Timetable ---
  const masterRows: any[] = [
    [`TMS SL - MASTER SCHOOL TIMETABLE`],
    [`School: ${schoolName}`],
    [`Generated: ${new Date().toLocaleString()}`],
    [],
    ['Day', 'Period', 'Class / Section', 'Subject', 'Teacher', 'Room', 'Double Period'],
  ];

  days.forEach((day) => {
    for (let p = 1; p <= bellSchedule.periods_per_day; p++) {
      const matchingSlots = slots.filter((s) => s.day === day && s.periodIndex === p);
      if (matchingSlots.length === 0) {
        masterRows.push([day, `P${p}`, 'Free / No class', '-', '-', '-', 'No']);
      } else {
        matchingSlots.forEach((slot) => {
          const cls = classes.find((c) => c.id === slot.classId);
          const tch = teachers.find((t) => t.id === slot.teacherId);
          masterRows.push([
            day,
            `P${p}`,
            cls ? cls.name : 'Unknown Class',
            slot.subjectName,
            tch ? tch.name : 'Unknown Teacher',
            slot.room || cls?.room || 'Standard',
            slot.isDoublePeriod ? 'Yes' : 'No',
          ]);
        });
      }
    }
  });

  const masterSheet = XLSX.utils.aoa_to_sheet(masterRows);
  XLSX.utils.book_append_sheet(workbook, masterSheet, 'Master Timetable');

  // --- SHEET 2: Class Timetables ---
  const classRows: any[] = [
    [`CLASS-WISE TIMETABLES`],
    [`School: ${schoolName}`],
    [],
  ];

  classes.forEach((cls) => {
    classRows.push([`=== ${cls.name} (Room: ${cls.room}) ===`]);
    const periodHeader = ['Day', ...Array.from({ length: bellSchedule.periods_per_day }, (_, i) => `P${i + 1}`)];
    classRows.push(periodHeader);

    days.forEach((day) => {
      const row = [day];
      for (let p = 1; p <= bellSchedule.periods_per_day; p++) {
        const slot = slots.find((s) => s.classId === cls.id && s.day === day && s.periodIndex === p);
        if (slot) {
          const tch = teachers.find((t) => t.id === slot.teacherId);
          row.push(`${slot.subjectName} (${tch ? tch.name : 'Teacher'})`);
        } else {
          row.push('Free');
        }
      }
      classRows.push(row);
    });
    classRows.push([]);
  });

  const classSheet = XLSX.utils.aoa_to_sheet(classRows);
  XLSX.utils.book_append_sheet(workbook, classSheet, 'Class Timetables');

  // --- SHEET 3: Teacher Workload Summary ---
  const teacherRows: any[] = [
    [`TEACHER WORKLOAD SUMMARY`],
    [`School: ${schoolName}`],
    [],
    ['Teacher Name', 'Subject Specialties', 'Max Daily Limit', 'Off Days', 'Total Weekly Periods Assigned', 'Capacity %'],
  ];

  teachers.forEach((tch) => {
    const assignedSlots = slots.filter((s) => s.teacherId === tch.id);
    const weeklyMax = tch.max_periods_per_day * 5;
    const capacity = weeklyMax > 0 ? Math.round((assignedSlots.length / weeklyMax) * 100) : 0;
    teacherRows.push([
      tch.name,
      tch.subjects,
      `${tch.max_periods_per_day} periods/day`,
      tch.off_days || 'None',
      assignedSlots.length,
      `${capacity}%`,
    ]);
  });

  const teacherSheet = XLSX.utils.aoa_to_sheet(teacherRows);
  XLSX.utils.book_append_sheet(workbook, teacherSheet, 'Teacher Workload');

  // Write file
  const sanitizedName = schoolName.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30);
  XLSX.writeFile(workbook, `TMS_SL_Timetable_${sanitizedName || 'Export'}.xlsx`);
};

/**
 * 3. PDF Export (using jspdf and jspdf-autotable)
 * Produces clean A4 printable PDF with School name header, Grid table of periods,
 * and Teacher / Principal signature space.
 */
export const exportTimetableToPDF = (params: {
  schoolName: string;
  bellSchedule: BellSchedule;
  classes: ClassSection[];
  teachers: TeacherRecord[];
  slots: TimetableSlot[];
  selectedClassId?: string;
}) => {
  const { schoolName, bellSchedule, classes, teachers, slots, selectedClassId } = params;
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const targetClass = classes.find((c) => c.id === selectedClassId) || classes[0];
  const title = targetClass
    ? `OFFICIAL CLASS TIMETABLE - ${targetClass.name} (Room ${targetClass.room})`
    : 'OFFICIAL SCHOOL MASTER TIMETABLE';

  // Header Title
  doc.setFontSize(18);
  doc.setTextColor(0, 51, 102);
  doc.text(schoolName?.trim() || 'Official School Timetable', 14, 16);

  doc.setFontSize(12);
  doc.setTextColor(80, 80, 80);
  doc.text(title, 14, 24);

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Academic Year: ${new Date().getFullYear()} | Generated on: ${new Date().toLocaleDateString()}`, 14, 30);

  // Table columns & rows
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
  const columns = ['Day', ...Array.from({ length: bellSchedule.periods_per_day }, (_, i) => `P${i + 1}`)];

  const bodyData = days.map((day) => {
    const row = [day];
    for (let p = 1; p <= bellSchedule.periods_per_day; p++) {
      let slot: TimetableSlot | undefined;
      if (targetClass) {
        slot = slots.find((s) => s.classId === targetClass.id && s.day === day && s.periodIndex === p);
      } else {
        slot = slots.find((s) => s.day === day && s.periodIndex === p);
      }

      if (slot) {
        const tch = teachers.find((t) => t.id === slot?.teacherId);
        const prefix = slot.isDoublePeriod ? '⚡ ' : '';
        row.push(`${prefix}${slot.subjectName}\n(${tch ? tch.name.split(' ')[0] : 'Staff'})`);
      } else {
        row.push('-');
      }
    }
    return row;
  });

  autoTable(doc, {
    head: [columns],
    body: bodyData,
    startY: 35,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 51, 102],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
    },
    bodyStyles: {
      halign: 'center',
      valign: 'middle',
      fontSize: 9,
      cellPadding: 4,
    },
    alternateRowStyles: {
      fillColor: [245, 248, 252],
    },
  });

  // Footer: Signature Lines
  const finalY = (doc as any).lastAutoTable?.finalY || 150;
  const pageHeight = doc.internal.pageSize.getHeight();
  const sigY = Math.min(finalY + 25, pageHeight - 20);

  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);

  // 3 Signature boxes
  doc.line(20, sigY, 75, sigY);
  doc.text('Prepared By (Timetable In-Charge)', 20, sigY + 5);

  doc.line(115, sigY, 175, sigY);
  doc.text('Verified By (Sectional Head)', 115, sigY + 5);

  doc.line(215, sigY, 275, sigY);
  doc.text('Approved By (Principal / Supervisor)', 215, sigY + 5);

  doc.save(`TMS_SL_Timetable_${targetClass ? targetClass.name.replace(/\s+/g, '_') : 'Master'}.pdf`);
};
